###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /docker
        volumes:
          - ./phpdocker/postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=pvvmdb
            - POSTGRES_PASSWORD=pvvmdb
            - POSTGRES_DB=pvvmdb
        ports:
            - '3014:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /docker
        volumes:
            - ./src:/docker
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '3010:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /docker
        volumes:
            - ./src:/docker
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
